--- # webserver
server:
  port: 8080
  context-path: /

--- # logging
logging:
  level:
#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://39.106.149.97:3306/family_mgr?useSSL=false
    username: yuandehong
    password: YanDeHong2018!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

  messages:
      basename: messages/messages
      cache-seconds: -1
      encoding: UTF-8

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
